spring:
  application:
    name: Config-Server

  profiles:
    active: native   # ✅ VERY IMPORTANT

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

server:
  port: 9000